METADATA = {
    "id": 1545,
    "name": "Find Kth Bit in Nth Binary String",
    "slug": "find-kth-bit-in-nth-binary-string",
    "category": "Math",
    "aliases": [],
    "tags": ["recursion", "string", "divide and conquer"],
    "difficulty": "medium",
    "time_complexity": "O(log k)",
    "space_complexity": "O(log k)",
    "description": "Find the k-th bit of the n-th binary string generated by a specific recursive rule without constructing the string.",
}

def solve(n: int, k: int) -> int:
    """
    Finds the k-th bit in the n-th binary string using the recursive properties.
    
    The string S(n) is constructed as: S(n) = S(n-1) + '1' + reverse(invert(S(n-1))).
    The length of S(n) is 2^n - 1.
    
    Args:
        n: The index of the binary string.
        k: The 1-based index of the bit to find.
        
    Returns:
        The bit (0 or 1) at the k-th position.
        
    Examples:
        >>> solve(1, 1)
        1
        >>> solve(2, 3)
        0
        >>> solve(3, 5)
        1
    """
    # Base case: S(1) is always "1"
    if n == 1:
        return 1

    # Calculate the length of the string S(n-1)
    # Length of S(n) is 2^n - 1, so length of S(n-1) is 2^(n-1) - 1
    prev_length = (1 << (n - 1)) - 1
    mid_index = prev_length + 1

    if k == mid_index:
        # The middle bit is always '1' according to the rule
        return 1
    elif k < mid_index:
        # If k is in the first half, it's the same as S(n-1)
        return solve(n - 1, k)
    else:
        # If k is in the second half, it's the inverted and reversed S(n-1)
        # To find the bit in the second half, we map k back to the first half.
        # The second half is reverse(invert(S(n-1))).
        # The position in the second half relative to the end is (length_of_Sn - k + 1)
        # However, a simpler way to handle reverse(invert(S(n-1))) is:
        # The bit at k in S(n) is 1 - (bit at (2^n - k) in S(n-1))
        # But using the symmetry: the bit at k is 1 - bit at (prev_length - (k - mid_index) + 1)
        # which simplifies to: 1 - bit at (2 * mid_index - k) in S(n-1)
        
        # Mapping k to the corresponding index in the first half:
        # The second half starts at mid_index + 1.
        # The last element of S(n) is the first element of S(n-1) inverted.
        # The element at k is the bit at (2 * mid_index - k) in S(n-1) inverted.
        new_k = 2 * mid_index - k
        return 1 - solve(n - 1, new_k)
