METADATA = {
    "id": 38,
    "name": "Count and Say",
    "slug": "count-and-say",
    "category": "String",
    "aliases": [],
    "tags": ["recursion", "strings", "simulation"],
    "difficulty": "medium",
    "time_complexity": "O(2^n)",
    "space_complexity": "O(2^n)",
    "description": "Generate the nth term of a sequence where each term is a verbal description of the previous term.",
}

def solve(n: int) -> str:
    """
    Generates the nth term of the 'Count and Say' sequence.

    The sequence starts with "1". Each subsequent term is generated by 
    reading the previous term aloud, counting the number of consecutive 
    identical digits.

    Args:
        n: The index of the term to generate (1-indexed).

    Returns:
        The nth term of the sequence as a string.

    Examples:
        >>> solve(1)
        '1'
        >>> solve(4)
        '1211'
    """
    if n <= 0:
        return ""
    
    current_sequence = "1"
    
    # We already have the 1st term, so we iterate n-1 times to reach the nth term
    for _ in range(n - 1):
        next_sequence_parts = []
        index = 0
        
        # Iterate through the current string to group identical consecutive characters
        while index < len(current_sequence):
            count = 1
            # Count how many times the current character repeats consecutively
            while (index + 1 < len(current_sequence) and 
                   current_sequence[index] == current_sequence[index + 1]):
                count += 1
                index += 1
            
            # Append the count and the character itself to the builder list
            next_sequence_parts.append(str(count))
            next_sequence_parts.append(current_sequence[index])
            index += 1
            
        # Join parts to form the next string in the sequence
        current_sequence = "".join(next_sequence_parts)
        
    return current_sequence
