METADATA = {
    "id": 2689,
    "name": "Extract Kth Character From The Rope Tree",
    "slug": "extract-kth-character-from-the-rope-tree",
    "category": "Math",
    "aliases": [],
    "tags": ["recursion", "math", "bit manipulation"],
    "difficulty": "medium",
    "time_complexity": "O(log k)",
    "space_complexity": "O(log k)",
    "description": "Find the kth character in a string generated by repeatedly applying a transformation rule.",
}

def solve(k: int) -> str:
    """
    Finds the kth character (1-indexed) in a string generated by a specific rule.
    
    The rule is: start with 'a'. In each step, the current string S becomes 
    S + transform(S), where transform(S) shifts each character to the next 
    alphabetical character (e.g., 'a' -> 'b', 'z' -> 'a').
    
    The key insight is that the character at index i (0-indexed) is determined 
    by the number of set bits in the binary representation of i. Each set bit 
    represents a transformation step where that specific position was part of 
    the 'new' half being appended.

    Args:
        k: The 1-indexed position of the character to extract.

    Returns:
        The character at the kth position.

    Examples:
        >>> solve(1)
        'a'
        >>> solve(2)
        'b'
        >>> solve(5)
        'b'
    """
    # Convert 1-indexed k to 0-indexed index
    index = k - 1
    
    # The number of times a character has been 'transformed' is equal to 
    # the number of set bits in its 0-indexed position.
    # For example:
    # index 0 (000): 0 bits -> 'a' + 0 = 'a'
    # index 1 (001): 1 bit  -> 'a' + 1 = 'b'
    # index 2 (010): 1 bit  -> 'a' + 1 = 'b'
    # index 3 (011): 2 bits -> 'a' + 2 = 'c'
    
    # count_set_bits calculates how many times the character was incremented
    # during the doubling process.
    set_bits_count = bin(index).count('1')
    
    # The character is 'a' shifted by the number of set bits, modulo 26.
    # ord('a') is 97.
    result_char_code = ord('a') + (set_bits_count % 26)
    
    return chr(result_char_code)
