METADATA = {
    "id": 3744,
    "name": "Find Kth Character in Expanded String",
    "slug": "find-kth-character-in-expanded-string",
    "category": "Math",
    "aliases": [],
    "tags": ["math", "bit_manipulation"],
    "difficulty": "easy",
    "time_complexity": "O(log k)",
    "space_complexity": "O(1)",
    "description": "Find the character at a specific index in a string generated by repeatedly applying a transformation rule.",
}

def solve(k: int) -> str:
    """
    Finds the kth character (0-indexed) in the expanded string.
    
    The expansion rule follows a pattern where each step doubles the string length
    and increments the characters based on their position. This is equivalent to
    observing that the character at index 'k' is determined by the number of 
    set bits (1s) in the binary representation of 'k'.
    
    Args:
        k (int): The 0-indexed position of the character to find.
        
    Returns:
        str: The character at the kth position.
        
    Examples:
        >>> solve(0)
        'a'
        >>> solve(5)
        'c'
    """
    # The problem describes a process similar to the Thue-Morse sequence 
    # or a variation of it. In each expansion step, the new characters 
    # are the old characters shifted by 1 (e.g., 'a' -> 'b', 'b' -> 'c').
    # The number of times a character has been 'shifted' is exactly equal 
    # to the number of times a '1' appears in the binary representation of k.
    
    # Count the number of set bits in k (population count)
    set_bits_count = bin(k).count('1')
    
    # The character is 'a' shifted by the number of set bits.
    # We use modulo 26 to ensure it stays within the lowercase English alphabet.
    result_char_code = ord('a') + (set_bits_count % 26)
    
    return chr(result_char_code)
