METADATA = {
    "id": 1088,
    "name": "Confusing Number II",
    "slug": "confusing-number-ii",
    "category": "Math",
    "aliases": [],
    "tags": ["cycle detection", "math", "floyd's cycle-finding algorithm"],
    "difficulty": "medium",
    "time_complexity": "O(log n)",
    "space_complexity": "O(1)",
    "description": "Determine if a number is confusing by checking if the sequence generated by replacing digits with their 9-complements enters a cycle that includes the original number.",
}

def solve(n: int) -> bool:
    """
    Determines if a number is a 'confusing number' using Floyd's Cycle-Finding algorithm.
    
    A number is confusing if the sequence generated by replacing each digit 
    with its 9-complement (9 - digit) eventually returns to the original number.

    Args:
        n: The integer to check.

    Returns:
        True if the number is confusing, False otherwise.

    Examples:
        >>> solve(1)
        True
        >>> solve(2)
        False
        >>> solve(10)
        True
    """
    
    def get_next(val: int) -> int:
        """Helper to calculate the next number in the sequence."""
        next_val = 0
        multiplier = 1
        temp = val
        # Process each digit to find its 9-complement
        while temp > 0:
            digit = temp % 10
            next_val += (9 - digit) * multiplier
            multiplier *= 10
            temp //= 10
        # Handle the case where the original number was 0 (though n >= 1 per constraints)
        if val == 0:
            return 9
        return next_val

    # Floyd's Cycle-Finding Algorithm (Tortoise and Hare)
    # We want to see if the cycle contains the starting value 'n'
    tortoise = get_next(n)
    hare = get_next(get_next(n))

    # Phase 1: Detect if a cycle exists
    while tortoise != hare:
        tortoise = get_next(tortoise)
        hare = get_next(get_next(hare))

    # Phase 2: Check if the detected cycle contains the original number 'n'
    # If the cycle contains 'n', the tortoise (or hare) will eventually hit 'n'
    # while traversing the cycle.
    curr = tortoise
    while True:
        if curr == n:
            return True
        curr = get_next(curr)
        if curr == tortoise:
            break

    return False
