METADATA = {
    "id": 3307,
    "name": "Find the K-th Character in String Game II",
    "slug": "find-the-k-th-character-in-string-game-ii",
    "category": "Math",
    "aliases": [],
    "tags": ["bit_manipulation", "math"],
    "difficulty": "hard",
    "time_complexity": "O(log k)",
    "space_complexity": "O(1)",
    "description": "Find the k-th character in a string generated by repeatedly applying a transformation rule involving an integer k.",
}

def solve(k: int, operations: list[int]) -> str:
    """
    Finds the k-th character (1-indexed) in the string generated by the game rules.

    The string starts as 'a'. In each operation i, the current string is appended 
    with a transformed version where each character is shifted by operations[i].
    The transformation follows a pattern similar to the Thue-Morse sequence, 
    where the character at index 'idx' depends on the bits set in 'idx'.

    Args:
        k: The 1-indexed position of the character to find.
        operations: A list of integers representing the shift applied in each step.

    Returns:
        The character at the k-th position.

    Examples:
        >>> solve(5, [0, 1])
        'b'
        >>> solve(10, [1, 1, 1, 1, 1])
        'd'
    """
    # Convert k to 0-indexed for bit manipulation logic
    target_index = k - 1
    
    # The total shift applied to the initial character 'a' is the sum of 
    # operations[i] for all i where the i-th bit of target_index is set.
    # This is because the i-th operation doubles the string length, 
    # effectively deciding whether the character at target_index 
    # was part of the original string or the newly appended transformed string.
    total_shift = 0
    
    # We iterate through the bits of target_index.
    # If the i-th bit is 1, it means the i-th operation contributed to the 
    # character at this position.
    for i in range(len(operations)):
        # Check if the i-th bit is set in target_index
        if (target_index >> i) & 1:
            total_shift += operations[i]
            
    # The character is 'a' shifted by the total accumulated shift.
    # We use modulo 26 to ensure the shift stays within the alphabet range.
    result_char_code = ord('a') + (total_shift % 26)
    
    return chr(result_char_code)
