METADATA = {
    "id": 3304,
    "name": "Find the K-th Character in String Game I",
    "slug": "find-the-k-th-character-in-string-game-i",
    "category": "Math",
    "aliases": [],
    "tags": ["bit_manipulation", "math"],
    "difficulty": "easy",
    "time_complexity": "O(log k)",
    "space_complexity": "O(1)",
    "description": "Find the k-th character in a string generated by repeatedly appending a transformed version of the current string.",
}

def solve(k: int) -> str:
    """
    Finds the k-th character in the string generated by the game rules.
    
    The game starts with "a". In each step, the current string is transformed 
    by shifting each character to its next character in the alphabet 
    (e.g., 'a' -> 'b', 'z' -> 'a') and appended to the original string.
    
    The pattern follows the Thue-Morse sequence logic: the character at 
    index i is determined by the number of set bits in the binary 
    representation of i. Specifically, the character is ('a' + popcount(i)) % 26.

    Args:
        k: The 1-based index of the character to find.

    Returns:
        The k-th character as a string.

    Examples:
        >>> solve(5)
        'b'
        >>> solve(1)
        'a'
    """
    # The problem uses 1-based indexing for k, but the bit manipulation 
    # logic relies on 0-based indexing.
    index = k - 1
    
    # The number of times a character has been "incremented" is equal to 
    # the number of set bits (1s) in its 0-based index.
    # For example:
    # index 0 (000): 0 bits -> 'a'
    # index 1 (001): 1 bit  -> 'b'
    # index 2 (010): 1 bit  -> 'b'
    # index 3 (011): 2 bits -> 'c'
    set_bits_count = bin(index).count('1')
    
    # Calculate the character by shifting 'a' by the number of increments.
    # We use modulo 26 to ensure it wraps around the alphabet.
    result_char_code = ord('a') + (set_bits_count % 26)
    
    return chr(result_char_code)
