METADATA = {
    "id": 779,
    "name": "K-th Symbol in Grammar",
    "slug": "k-th-symbol-in-grammar",
    "category": "Math",
    "aliases": [],
    "tags": ["recursion", "math", "bit_manipulation"],
    "difficulty": "medium",
    "time_complexity": "O(log k)",
    "space_complexity": "O(log k)",
    "description": "Find the k-th symbol in the k-th row of a grammar sequence generated by specific rules.",
}

def solve(k: int) -> int:
    """
    Finds the k-th symbol in the k-th row of the grammar sequence.
    
    The grammar rules are:
    Row 1: 0
    Row 2: 01 (0 becomes 01)
    Row 3: 0110 (0 becomes 01, 1 becomes 10)
    
    Key Insight:
    Each row is twice the length of the previous row.
    The first half of row 'n' is identical to row 'n-1'.
    The second half of row 'n' is the bitwise complement of row 'n-1'.

    Args:
        k: The 1-indexed position of the symbol to find.

    Returns:
        The integer value (0 or 1) at the k-th position.

    Examples:
        >>> solve(1)
        0
        >>> solve(2)
        1
        >>> solve(6)
        0
    """
    # Base case: The first row always contains only '0'
    if k == 1:
        return 0

    # Calculate the length of the previous row. 
    # Since row length doubles each time, we find the midpoint of the current row.
    # We can determine the midpoint by finding the largest power of 2 less than k.
    # However, a simpler way is to observe the structure:
    # If k is in the first half, it's the same as k in the previous row.
    # If k is in the second half, it's the complement of (k - midpoint) in the previous row.
    
    # To find the midpoint without knowing the exact row number, 
    # we find the largest power of 2 that is strictly less than k.
    # This power of 2 represents the length of the previous row.
    
    # Find the largest power of 2 less than k
    # Example: k=6. Midpoint is 4.
    midpoint = 1
    while midpoint < k:
        midpoint <<= 1
    midpoint >>= 1

    # If k is in the first half (k <= midpoint), the value is the same as in the previous row.
    if k <= midpoint:
        return solve(k)
    
    # If k is in the second half, the value is the complement of the value at (k - midpoint).
    # We use 1 - solve(...) to flip 0 to 1 and 1 to 0.
    else:
        return 1 - solve(k - midpoint)

def solve_iterative(k: int) -> int:
    """
    An iterative version of the solution using bit manipulation.
    
    The k-th symbol is determined by the number of set bits in (k-1).
    Specifically, the value is (count_set_bits(k-1) % 2).
    This is because each time we move to the second half of a row, 
    we are essentially adding a bit that flips the value.
    
    Args:
        k: The 1-indexed position of the symbol to find.

    Returns:
        The integer value (0 or 1) at the k-th position.
    """
    # The pattern follows the Thue-Morse sequence logic.
    # The value at index i (0-indexed) is the parity of the number of 1s in the binary representation of i.
    return bin(k - 1).count('1') % 2
