METADATA = {
    "id": 906,
    "name": "Super Palindromes",
    "slug": "super-palindromes",
    "category": "Math",
    "aliases": [],
    "tags": ["math", "palindrome", "string"],
    "difficulty": "hard",
    "time_complexity": "O(n^0.25)",
    "space_complexity": "O(1)",
    "description": "Find the number of super-palindromes less than or equal to n, where a super-palindrome is a palindrome whose square is also a palindrome.",
}

def solve(n: int) -> int:
    """
    Finds the number of super-palindromes less than or equal to n.
    
    A super-palindrome is a number whose square is also a palindrome.
    The algorithm generates palindromes (roots), squares them, and checks 
    if the square is a palindrome and within the limit n.

    Args:
        n: The upper bound (inclusive).

    Returns:
        The count of super-palindromes <= n.

    Examples:
        >>> solve(100)
        4
        >>> solve(100000000000000)
        7
    """
    def is_palindrome(val: int) -> bool:
        s = str(val)
        return s == s[::-1]

    super_palindrome_count = 0
    
    # We need to find palindromes whose square is <= n.
    # This means the palindrome itself must be <= sqrt(n).
    # Since n can be up to 10^18, sqrt(n) is up to 10^9.
    # We generate palindromes by constructing them from their "half".
    # For a palindrome up to 10^9, the half is at most 10^5.
    
    # We iterate through all possible "half" numbers to construct palindromes.
    # A half of 123 can form 12321 (odd length) or 123321 (even length).
    for i in range(1, 100000):
        s = str(i)
        
        # Case 1: Odd length palindrome (e.g., 123 -> 12321)
        # We take the string, reverse all but the last char, and append.
        p1 = int(s + s[:-1][::-1])
        square1 = p1 * p1
        if square1 <= n:
            if is_palindrome(square1):
                super_palindrome_count += 1
        
        # Case 2: Even length palindrome (e.g., 123 -> 123321)
        # We take the string, reverse it, and append.
        p2 = int(s + s[::-1])
        square2 = p2 * p2
        if square2 <= n:
            if is_palindrome(square2):
                super_palindrome_count += 1
                
    # Note: The loop range 100,000 covers palindromes up to 10^9 (9 digits + 1 digit).
    # However, the logic above might double count or miss edge cases if not careful.
    # Let's refine the generation to ensure we cover all roots up to 10^9.
    # Actually, the loop up to 10^5 covers roots up to 10^5 (even) and 10^5 (odd) -> 10^10.
    # Since sqrt(10^18) = 10^9, we need to ensure we cover roots up to 10^9.
    # A root of 10^9 is generated by a half of 10^5 (e.g., 100000 -> 10000000001).
    # Wait, the loop should go up to 10^5 to cover roots up to 10^9.
    # Let's re-verify: 
    # If i = 99999, p1 = 999999999 (9 digits), p2 = 9999999999 (10 digits).
    # sqrt(10^18) is 10^9. So p1 and p2 can reach 10^9.
    
    # The current loop covers roots up to ~10^10. 
    # But we must handle the case where square1 or square2 exceeds n.
    # The logic above is slightly flawed because it doesn't account for the fact 
    # that p1 and p2 are not generated in strictly increasing order.
    # However, since we only care about the count, we can collect them in a set.
    
    # Let's rewrite the generation to be more robust.
    results = set()
    for i in range(1, 100000):
        s = str(i)
        
        # Odd length
        p1 = int(s + s[:-1][::-1])
        if p1 * p1 <= n:
            if is_palindrome(p1 * p1):
                results.add(p1 * p1)
        
        # Even length
        p2 = int(s + s[::-1])
        if p2 * p2 <= n:
            if is_palindrome(p2 * p2):
                results.add(p2 * p2)
                
    # There is one edge case: the loop only goes to 10^5.
    # If n = 10^18, sqrt(n) = 10^9.
    # A 9-digit palindrome like 999,999,999 is generated by i=99999 (s='99999', p1='999999999').
    # A 10-digit palindrome like 1,000,000,001 is generated by i=10000 (s='10000', p2='1000000001').
    # So i up to 10^5 is sufficient to generate all palindromes up to 10^10.
    
    return len(results)
